Update devsecops.yml

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -7,8 +7,7 @@ on:
 
   workflow_dispatch:
 
-# Prevent multiple workflow runs from modifying main
-# at the same time.
+# Prevent multiple workflows from changing main simultaneously
 concurrency:
   group: sudoku-devsecops-main
   cancel-in-progress: true
@@ -18,6 +17,7 @@ permissions:
 
 env:
   APP_NAME: sudoko-game
+  DOCKERHUB_USERNAME: veerumatta
   DOCKER_IMAGE: veerumatta/sudoko-game
 
 jobs:
@@ -30,7 +30,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
 
@@ -39,7 +38,7 @@ jobs:
           set -e
 
           echo "======================================"
-          echo "Checking application files..."
+          echo "Checking application files"
           echo "======================================"
 
           test -f index.html
@@ -53,6 +52,7 @@ jobs:
 
           test -f argocd/application.yaml
 
+          echo "All required files found."
           echo "Application validation successful."
 
 
@@ -66,7 +66,6 @@ jobs:
     needs: build
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
         with:
@@ -95,7 +94,6 @@ jobs:
     needs: build
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
 
@@ -108,7 +106,6 @@ jobs:
             -o snyk
 
           chmod +x snyk
-
           sudo mv snyk /usr/local/bin/snyk
 
       - name: Check Snyk version
@@ -119,6 +116,11 @@ jobs:
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         run: |
+          if [ -z "$SNYK_TOKEN" ]; then
+            echo "ERROR: SNYK_TOKEN is not configured."
+            exit 1
+          fi
+
           snyk auth "$SNYK_TOKEN"
 
       - name: Run Snyk scan
@@ -140,7 +142,6 @@ jobs:
       - snyk
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
 
@@ -168,11 +169,12 @@ jobs:
     needs: docker-build
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Build image for Trivy
+      # GitHub Actions jobs use separate runners,
+      # therefore the image must be rebuilt here.
+      - name: Build Docker image for Trivy
         run: |
           set -e
 
@@ -191,7 +193,7 @@ jobs:
 
 
   # ============================================================
-  # 6. PUSH IMAGE TO DOCKER HUB
+  # 6. LOGIN + PUSH TO DOCKER HUB
   # ============================================================
   push-image:
     name: Push Image to Docker Hub
@@ -200,9 +202,16 @@ jobs:
     needs: trivy
 
     steps:
-
       - name: Checkout source code
         uses: actions/checkout@v4
+
+      # --------------------------------------------------------
+      # Verify Docker Hub configuration
+      # --------------------------------------------------------
+      - name: Verify Docker Hub configuration
+        run: |
+          echo "Docker Hub username: ${{ env.DOCKERHUB_USERNAME }}"
+          echo "Docker image: ${{ env.DOCKER_IMAGE }}"
 
       # --------------------------------------------------------
       # Login to Docker Hub
@@ -210,48 +219,64 @@ jobs:
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
+          registry: docker.io
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       # --------------------------------------------------------
-      # Build Docker image
+      # Build image
       # --------------------------------------------------------
       - name: Build Docker image
         run: |
           set -e
 
           docker build \
-            -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
-            -t ${{ env.DOCKER_IMAGE }}:latest \
+            -t docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
+            -t docker.io/${{ env.DOCKER_IMAGE }}:latest \
             .
+
+      # --------------------------------------------------------
+      # Show image
+      # --------------------------------------------------------
+      - name: Show Docker image
+        run: |
+          docker images | grep sudoko-game || true
 
       # --------------------------------------------------------
       # Push SHA image
       # --------------------------------------------------------
       - name: Push SHA image to Docker Hub
         run: |
+          set -e
+
           docker push \
-            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
+            docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
 
       # --------------------------------------------------------
       # Push latest image
       # --------------------------------------------------------
       - name: Push latest image to Docker Hub
         run: |
+          set -e
+
           docker push \
-            ${{ env.DOCKER_IMAGE }}:latest
+            docker.io/${{ env.DOCKER_IMAGE }}:latest
 
       # --------------------------------------------------------
-      # Display image information
+      # Final Docker Hub information
       # --------------------------------------------------------
-      - name: Display Docker image information
+      - name: Display Docker Hub image
         run: |
-          echo "======================================"
-          echo "Docker Hub Image"
-          echo "======================================"
+          echo "=============================================="
+          echo "Docker Hub Push Successful"
+          echo "=============================================="
 
-          echo "${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
-          echo "${{ env.DOCKER_IMAGE }}:latest"
+          echo "SHA:"
+          echo "docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
+
+          echo ""
+          echo "Latest:"
+          echo "docker.io/${{ env.DOCKER_IMAGE }}:latest"
 
 
   # ============================================================
@@ -269,7 +294,7 @@ jobs:
     steps:
 
       # --------------------------------------------------------
-      # Checkout main branch
+      # Checkout latest main
       # --------------------------------------------------------
       - name: Checkout source code
         uses: actions/checkout@v4
@@ -286,7 +311,7 @@ jobs:
           git config user.email "veeruveerareddy9@gmail.com"
 
       # --------------------------------------------------------
-      # Synchronize with latest main
+      # Get latest remote main
       # --------------------------------------------------------
       - name: Synchronize with latest main
         run: |
@@ -297,6 +322,9 @@ jobs:
           git checkout main
 
           git reset --hard origin/main
+
+          echo "Current branch:"
+          git branch --show-current
 
           echo "Current commit:"
           git log -1 --oneline
@@ -309,26 +337,26 @@ jobs:
           set -e
 
           echo "======================================"
-          echo "Updating Kubernetes deployment..."
+          echo "Updating Kubernetes image"
           echo "======================================"
 
           sed -i \
-            "s|^[[:space:]]*image:.*|        image: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}|" \
+            "s|^[[:space:]]*image:.*|        image: docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}|" \
             k8s/deployment.yaml
 
       # --------------------------------------------------------
-      # Show updated deployment
+      # Show deployment
       # --------------------------------------------------------
       - name: Show updated deployment
         run: |
           echo "======================================"
-          echo "Updated Kubernetes Deployment"
+          echo "Updated deployment.yaml"
           echo "======================================"
 
           cat k8s/deployment.yaml
 
       # --------------------------------------------------------
-      # Commit Kubernetes change
+      # Commit manifest
       # --------------------------------------------------------
       - name: Commit Kubernetes change
         run: |
@@ -344,7 +372,7 @@ jobs:
           fi
 
       # --------------------------------------------------------
-      # Push Kubernetes change
+      # Push manifest
       # --------------------------------------------------------
       - name: Push Kubernetes change
         run: |
@@ -362,7 +390,7 @@ jobs:
             fi
 
             echo "Push rejected."
-            echo "Synchronizing with latest remote main..."
+            echo "Fetching latest main..."
 
             git fetch origin main
 
@@ -370,8 +398,7 @@ jobs:
 
           done
 
-          echo "Failed to push Kubernetes manifest after 3 attempts."
-
+          echo "Failed to push Kubernetes manifest."
           exit 1
 
 
@@ -402,7 +429,7 @@ jobs:
           sudo mv argocd /usr/local/bin/argocd
 
       # --------------------------------------------------------
-      # Check Argo CD CLI
+      # Check Argo CD version
       # --------------------------------------------------------
       - name: Argo CD version
         run: |
@@ -411,32 +438,31 @@ jobs:
       # --------------------------------------------------------
       # Validate Argo CD server
       # --------------------------------------------------------
-      - name: Check Argo CD server
+      - name: Validate Argo CD server
         env:
           ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
         run: |
           set -e
 
-          echo "Checking Argo CD server configuration..."
-
-          if [[ -z "$ARGOCD_SERVER" ]]; then
+          if [ -z "$ARGOCD_SERVER" ]; then
             echo "ERROR: ARGOCD_SERVER secret is empty."
             exit 1
           fi
 
           if [[ "$ARGOCD_SERVER" == *"localhost"* ]]; then
-            echo "ERROR: ARGOCD_SERVER cannot use localhost."
+            echo "ERROR: ARGOCD_SERVER cannot contain localhost."
             exit 1
           fi
 
           if [[ "$ARGOCD_SERVER" == *"//"* ]]; then
             echo "ERROR: ARGOCD_SERVER must be HOST:PORT."
-            echo "Example: 18.145.229.8:31102"
+            echo "Example:"
+            echo "18.145.229.8:31102"
             exit 1
           fi
 
-          echo "Argo CD server configuration is valid."
-
+          echo "Argo CD server:"
+          echo "$ARGOCD_SERVER"
 
       # --------------------------------------------------------
       # Login to Argo CD
@@ -453,39 +479,41 @@ jobs:
             --grpc-web \
             --insecure
 
-
       # --------------------------------------------------------
-      # Check Argo CD application
+      # Check application
       # --------------------------------------------------------
       - name: Check Argo CD application
         run: |
+          set -e
+
           argocd app get sudoko-game \
             --grpc-web
-
 
       # --------------------------------------------------------
       # Sync application
       # --------------------------------------------------------
       - name: Sync Argo CD application
         run: |
+          set -e
+
           argocd app sync sudoko-game \
             --grpc-web
 
-
       # --------------------------------------------------------
-      # Wait for application health
+      # Wait for application
       # --------------------------------------------------------
       - name: Wait for application health
         run: |
+          set -e
+
           argocd app wait sudoko-game \
             --sync \
             --health \
             --timeout 300 \
             --grpc-web
 
-
       # --------------------------------------------------------
-      # Final deployment information
+      # Deployment successful
       # --------------------------------------------------------
       - name: Deployment successful
         run: |
@@ -495,7 +523,7 @@ jobs:
 
           echo ""
           echo "Docker Image:"
-          echo "${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
+          echo "docker.io/${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
 
           echo ""
           echo "Argo CD Application:"
